import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import dotenv from "dotenv";
import connectDB from "./config/db";
import authRoutes from "./route/authRoutes";
import userRoutes from "./route/userRoutes";
import envelopeRoutes from "./route/envelopeRoutes";
import transactionRoutes from "./route/transactionRoutes";
import savingsRoutes from "./route/savingsRoutes";
import { errorHandler } from "./middleware/errorHandler";
dotenv.config();
connectDB();
const app = express();
app.use(express.json()); 
app.use(cors({ origin: "http://localhost:3000", credentials: true }));
app.use(cookieParser());
app.use(express.json());
app.use("/api/v1/auth", authRoutes);
app.use("/api/v1/user", userRoutes);
app.use("/api/v1/envelopes", envelopeRoutes);
app.use("/api/v1/transactions", transactionRoutes);
app.use("/api/v1/savings", savingsRoutes);
app.get("/health", (_, res) => res.send("OK"));
app.use(errorHandler);
const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
